### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by ceoaliongroo**

### CODE REVIEW

**Comment by robertjd** [comment]
Thanks for this!  Curious though, why the reason for declaring `path` as a dependency?

**Comment by robertjd** [comment]
Also, how are you finding the library?  Feedback is very welcome!

**Comment by physicalweb** [comment]
+daniel

Daniel? Any feedback?  Thanks,

**Comment by robertjd** [comment]
@physicalweb FYI we're changing this repo name from `stormpath-sdk-angular` to `stormpath-sdk-angularjs`

Please update your bower.json with the new name - thanks!

**Pull request merged**
