### PR TITLE
Export name bug

### LINKED ISSUE #80: Wrong module name in module.exports
Yeah, so you have

```
module.exports = 'ui.router';
```

in `dist/stormpath-sdk-angularjs.js`. Surely that should be

```
module.exports = 'stormpath';
```

### PR DESCRIPTION
**Pull request by timothyej**
Fixes #80.

This PR makes it possible to include the SDK using browserify or webpack.
- `stormpath-sdk-angularjs.js` exports `'stormpath'` instead of `'ui.router'`
- `stormpath-sdk-angularjs.tpls.js` exports `'stormpath.templates`
### How to verify
1. Checkout this branch
2. Copy the `dist/` folder into your AngularJS project (you can use [this boilerplate](https://github.com/basti1302/angular-browserify))
3. Modify your `package.json` to include these lines:
   
   ``` json
   "browser": {
     "stormpath": "./lib/stormpath-sdk-angularjs.js",
     "stormpath.templates": "./lib/stormpath-sdk-angularjs.tpls.js"
   }
   ```
4. In `app/js/app.js`, require `stormpath` and `stormpath.templates` in dependencies:
   
   ``` javascript
   var app = angular.module('todoApp', [
     require('angular-route'),
     require('stormpath'),
     require('stormpath.templates')
   ]);
   ```
5. Make sure that the templates still work by using the login directive in `app/views/todos.html`:
   
   ``` html
   ...
   <div sp-login-form></div>
   ...
   ```
6. Build the app:
   
   ``` bash
   $ gulp
   ```
7. Serve the app using the [`SPA Development Server`](https://github.com/stormpath/stormpath-spa-dev-server):
   
   ``` bash
   $ stormpath-spa-dev-server <path-to-your-app>/app/dist
   ```
8. Verify that the form gets rendered and that the SDK is included properly
9. To verify all functionality, please exchange the `ngRouter` for `UI Router` instead

### CODE REVIEW

**Comment by robertjd** [comment]
I have the same question RE templates.  Perhaps that file needs the same
banner but with 'stormpath.templates' as the export value

**Comment by timothyej** [comment]
Yes, I'm looking at it now, will see if `html2js` (which is generating the file) has any options like that.

**Comment by timothyej** [comment]
Seems like that: https://www.npmjs.com/package/grunt-common-html2js#options-fileheaderstring

**Comment by timothyej** [comment]
@robertjd and @typerandom please review! :)

**Comment by robertjd** [comment]
Looks good, thanks @timothyej !

**Pull request merged**
