### PR TITLE
fix: remove not necessary dependency.

### PR DESCRIPTION
**Pull request by ceoaliongroo**
Great!!

Yes, was a confusion. removing path dependency.

The sdk works fine, now i'll installing the server into heroku, and try the sdk in the application. Keep in touch to the next step after.

thanks

### CODE REVIEW

**Comment by robertjd** [comment]
Got it :)

We just renamed the repo to have "js" on the end of the name - could you update this PR to just remove the path dependency?  Thanks :)

**Comment by ceoaliongroo** [comment]
Yes, i'll see work on it

**Comment by ceoaliongroo** [comment]
updated

**Comment by robertjd** [comment]
thanks!

**Pull request merged**
