### PR TITLE
Framework spec compliance

### LINKED ISSUE #105: Update to work with upcoming express-stormpath@3.0
With these changes I think we should move this library to 1.0 - ping @timothyej 
### Todo
- [x] Add X-Stormpath-Agent header (#106)
- [x] Implement the login view model (#108)
- [x] Implement the registration view model (#109)
- [x] Implement the new JSON error responses (#110)
- [x] Change logout to use POST request (#116)

### PR DESCRIPTION
**Pull request by timothyej**
Fixes #105.

### CODE REVIEW

**Comment by robertjd** [comment]
Thanks @timothyej !  I'd like to see a few more documentation changes:
- In the changelog, please describe how this new release allows you to have a dynamic configuration form.  We like to promote new features in the changelog :)
- Remove the SPA_CONFIG_ENDPOINT documentation
- Update the server integration guide to mention that the login and registration endpoints need to return JSON views.  You can point them to the express documentation for the format of the JSON view, i added examples of the default response to the login and registration sections of that documentation.

**Comment by rorheden** [comment]
Besides Roberts comments, I have tried this and all the features I have tried works as expected! :+1:

**Comment by timothyej** [comment]
Good points, @robertjd! I will push new commits directly to this branch.

> Remove the SPA_CONFIG_ENDPOINT documentation

https://github.com/stormpath/stormpath-sdk-angularjs/pull/121/files#diff-82b850434a6b83385aa931b770a85918L189

Or is there anything else I'm missing?

**Comment by timothyej** [comment]
@robertjd, I've addressed your comments, please have a look:

> In the changelog, please describe how this new release allows you to have a dynamic configuration form. We like to promote new features in the changelog :)

a5f19654cf4099784e237a9585723c7185f421c7

> Remove the SPA_CONFIG_ENDPOINT documentation

Done [previously](https://github.com/stormpath/stormpath-sdk-angularjs/pull/121/files#diff-82b850434a6b83385aa931b770a85918L189) unless there's something I'm missing.

> Update the server integration guide to mention that the login and registration endpoints need to return JSON views. You can point them to the express documentation for the format of the JSON view, i added examples of the default response to the login and registration sections of that documentation.

288a97a94cbe4cb6c262841ff8ad33f09315354c

**Comment by robertjd** [comment]
Thanks for the updates, RE the SPA_CONFIG_ENDPOINT, I must have been reading the diff the wrong way.

**Pull request merged**
