### PR TITLE
Edited all documentation

### PR DESCRIPTION
**Pull request by drpalaric**
I've edited all the documentation in the repository. I've made the punctuation and spacing more consistent and I've corrected the spelling mistakes. There also was a semicolon that was missing from the example code, but I've fixed that. 

I haven't changed the spacing between sentences because it seems like you prefer two spaces after each sentence. Therefore, I've gone through the documentation and made two spaces after each sentence. I think there were only one or two instances where two spaces did not occur. 

Other changes that I have made were in the descriptions of the directives/services. Sometimes the descriptions were smashed together, making it difficult to read. Thus, when necessary, I separated the titles of each description/service by one space (top and bottom) so that it is easier to read as a whole. One more thing I have noticed, but did not change, is the @description in each JS file is sometimes at the beginning of the documentation and sometimes at the end. I wasn't sure if that is intentional, so I kept it as is. Perhaps you could tell me if you would like it to be always at the top of the documentation, instead of at the bottom, and I can change it.

### CODE REVIEW

**Comment by rdegges** [comment]
+1 This is quite possibly the most badass PR I've ever seen in my life. You are a true internet hero @AbdullahAlger.

<3333

**Comment by drpalaric** [comment]
Thanks @rdegges. I really like Stormpath and want others to like it too. It's freakin' awesome! Waiting for other developments.

**Comment by rdegges** [comment]
Thanks so much! Means a lot to all of us over here <33

@robertjd who runs this library will get back to ya soon ^^

**Comment by robertjd** [comment]
Thanks so much @AbdullahAlger!

You prompted me to question my double spacing after sentences.  A quick Google search tells me that I [may be over 40](http://www.cultofpedagogy.com/two-spaces-after-period/) because I use two spaces.  While that isn’t true (yet) I did, in fact, learn to type on a typewriter.  Perhaps it's time to let one of those spaces die :)

Regarding the location of the description tag, I’d propose the following ordering of tags, as it puts the larger sections at the end while keeping the terse information at the top:

```
@ngdoc
@name
@methodOf (or eventOf, etc)
@param
@returns
@description
@example
```

Thoughts?  I also agree that there should be a line between the description tag and the text that follows it.

Thanks again!  We’d love to send you a Stormpath T-Shirt, please reach us on support@stormpath.com and let us know where we can send it!

-Robert

**Comment by drpalaric** [comment]
@robertjd 

LOL. I almost fell out of my chair reading that two spaces equates to being over 40. I am not over the hill yet as well, and I learned to type on an Apple II. Actually, I use two spaces sometimes, but I have gotten into the habit of not doing it after my grad school supervisor kept complaining about it. She's British! I don't think it matters one way or the other. Consistency is the real issue. 

As far as the tags go, yes, I think you're right. After all, I am just a user. I think that most of them are ordered like that in the docs, but I will check to make sure. However, some are ordered:

```
@ngdoc
@name
@evenOf
@eventType
@description
@returns
@param
@example
```

I will go in and see about cleaning that up to organize it as you suggested. Going from tags that have less information to more information makes a lot of sense because you don't want the description to overwhelm the other documentation.  

Happy to contribute as best as I can to the project.

**Pull request merged**
