### PR TITLE
Support for ngRoute

### LINKED ISSUE #47: Support ngRoute
At the moment we only support UI Router for a routing mechanism, we want to support ngRoute as well

### PR DESCRIPTION
**Pull request by timothyej**
Closes #47.

This PR adds support for `ngRoute` (in addition to `UI Router`). It does so by exposing a new set of APIs, similar to the ones for `UI Router`.

It has the same feature set and the only difference in the API is the use of the word `route` instead of `state`.
### Notes
- I decided to keep it as separate APIs to not break backward compatibility. The code for this is a bit redundant, but this will be addressed in a later PR, which will break the API.
- When reviewing, see my two commits for easier overview
### To do
- [x] Provide an example app that is using `ngRoute` instead of `UI Router`
### How to verify
1. Checkout this branch
2. Build using `$ grunt dist --force`
3. Copy files from `dist/` into your Angular app folder
4. Make sure your app is using `ngRoute` instead of `UI Router` (e.g. `example/ng-route-app/`)
5. Verify that routing works at it should by navigating though your routes
6. Try to login and logout and verify that redirection is made correctly
7. Try to access protected routes when logged out and verify that you gets redirected to login
8. Try to access protected routes when logged in and verify that you can see them
9. Verify that the same behaviour works when you load the app at these routes in a new tab

### CODE REVIEW

**Comment by timothyej** [comment]
I've updated the PR with an example app that demonstrates the use of `ngRoute` together with this SDK.

**Comment by timothyej** [comment]
I've resolved the merge conflicts.

**Comment by robertjd** [comment]
Hey @timothyej - my apologies for taking so long to review this one.  

I'm having a problem with (8), in particular with the profile view.  If I'm logged in, navigate to /profile, then reload the page, I get a white screen.

I tried to fix it like this: https://github.com/robertjd/stormpath-sdk-angularjs/commit/8b6ef44ac6bdb467cc618f5f8f587d1e2da3b3d4

but it doesn't seem to have helped

Please see the other commits on my ng-route branch.  I have upgraded the express-stormpath dependency, and re-ordered the middleware in the ng-route example application.  The re-order fixes it so that the static assets aren't protected by api authentication, which is very slow.  This is the same fix that I made in the dashboard app.

Can you reproduce the reload on the /profile page and let me know what happens for you?  Thanks!

P.S.  The "state change interceptor" that I originally built feels overly complicated.   Using the "resolves" feature of UI Router and ng-route is probably much cleaner and angular-promise-esque.

**Comment by timothyej** [comment]
@robertjd I get the same problem. I'm looking into this now.

**Comment by timothyej** [comment]
I've fixed this in my latest commit: dc79e838e2b5d1e380f3915786e6e3d905432e14

Should you cherry-pick my commit (or just create a new one) into your branch, or should I cherry pick your commits into mine?

**Comment by robertjd** [comment]
Thanks @timothyej !

I can confirm that your latest commit does fix the problem RE reloading authenticated views.

Please ignore my commit that I linked to, that only for showing you what I had tried.

However, I would like to close this PR and open a new one that originates from this repository.  In the new PR, please don't commit the `dist/` assets (I only do that on release PRs, to avoid a conflict mess).

Also, please make the following fixes in the new example appliation:
- Re-order the middleware initialization, so that the public assets aren't protected by Stormpath authentication (this is not necessary and significantly slows down load times (see the dashboard-app example for ordering)
- Make these same changes that I made to the other example application: https://github.com/stormpath/stormpath-sdk-angularjs/commit/e7a0550124ae8c0793422fb4cc1c9c887bd9ddbd

Thanks again, almost done with this one!

**Comment by timothyej** [comment]
Closed in favour of #89. Thanks for the great review, @robertjd!

**Pull request closed without merging**
